- name: Get pki certificates and keys
  fetch:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/pki/"
    flat: yes
  with_items:
    - /etc/kubernetes/pki/ca.crt
    - /etc/kubernetes/pki/ca.key
    - /etc/kubernetes/pki/sa.pub
    - /etc/kubernetes/pki/sa.key
    - /etc/kubernetes/pki/front-proxy-ca.crt
    - /etc/kubernetes/pki/front-proxy-ca.key
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes
  changed_when: false # Local "buffer" must not notify any change. The changes if any will be notified by the copy

- name: Get custom control plane certificates
  fetch:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/pki/"
    flat: yes
  with_items:
    - /etc/kubernetes/pki/kube-controller-manager.crt
    - /etc/kubernetes/pki/kube-controller-manager.key
    - /etc/kubernetes/pki/kube-scheduler.crt
    - /etc/kubernetes/pki/kube-scheduler.key
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes
  changed_when: false # Local "buffer" must not notify any change. The changes if any will be notified by the copy
  when: kubernetes_pki is defined

- name: Get custom client_ca file
  fetch:
    src: "/etc/kubernetes/pki/client_ca.pem"
    dest: "{{ role_path }}/files/pki/"
    flat: yes
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes
  changed_when: false # Local "buffer" must not notify any change. The changes if any will be notified by the copy
  when: kubernetes_client_ca_file is defined

- name: Get etcd certificates
  fetch:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/pki/etcd/"
    flat: yes
  with_items:
    - /etc/kubernetes/pki/etcd/ca.crt
    - /etc/kubernetes/pki/etcd/ca.key
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes
  changed_when: false # Local "buffer" must not notify any change. The changes if any will be notified by the copy

- name: Ensure pki directory exists
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd

- name: Copy pki certificates and keys
  copy:
    src: "{{ role_path }}/files/pki/{{ item.src }}"
    dest: "/etc/kubernetes/pki/{{ item.src }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: "ca.crt", mode: "0644"}
    - {src: "ca.key", mode: "0600"}
    - {src: "sa.pub", mode: "0600"}
    - {src: "sa.key", mode: "0600"}
    - {src: "front-proxy-ca.crt", mode: "0644"}
    - {src: "front-proxy-ca.key", mode: "0600"}
    - {src: "etcd/ca.crt", mode: "0644"}
    - {src: "etcd/ca.key", mode: "0600"}

- name: Copy custom control plane certificates
  copy:
    src: "{{ role_path }}/files/pki/{{ item.src }}"
    dest: "/etc/kubernetes/pki/{{ item.src }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: "kube-controller-manager.crt", mode: "0644"}
    - {src: "kube-controller-manager.key", mode: "0600"}
    - {src: "kube-scheduler.crt", mode: "0644"}
    - {src: "kube-scheduler.key", mode: "0600"}
  when: kubernetes_pki is defined

- name: Copy custom client_ca file
  copy:
    src: "{{ role_path }}/files/pki/client_ca.pem"
    dest: "/etc/kubernetes/pki/client_ca.pem"
    mode: "0644"
  when: kubernetes_client_ca_file is defined

- name: Clean up local buffer
  file:
    state: absent
    path: "{{ role_path }}/files/pki"
  delegate_to: localhost
  run_once: yes
  changed_when: false
