- name: Get a join token
  command: 'kubeadm token create'
  register: join_token_raw
  when: join_token is not defined
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes

- name: Set the join_token fact for all play hosts
  set_fact:
    join_token: "{{ join_token_raw.stdout }}"
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  when: join_token is not defined
  run_once: yes

- name: Get the CA hash
  shell: |
    set -o pipefail;
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  args:
    executable: /bin/bash
  register: ca_hash_raw
  when: ca_hash is not defined
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes

- name: Set the ca_hash fact for all play hosts
  set_fact:
    ca_hash: "{{ ca_hash_raw.stdout }}"
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  when: ca_hash is not defined
  run_once: yes
