- name: Copy the kubeadm init config
  template:
    src: kubeadm_config.yaml.j2
    dest: /etc/kubeadm/config.yaml
    mode: 0755

- name: Initialise custom certificates
  include_tasks: init_master_pki.yml
  when: kubernetes_pki is defined

- name: Copy a client AC bundle
  copy:
    src: "{{ kubernetes_client_ca_file }}"
    dest: "/etc/kubernetes/pki/client_ca.pem"
    remote_src: no
    mode: "0644"
  when: kubernetes_client_ca_file is defined

- name: Checks if the master exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: first_master

- name: Set the fact already_initialized for all play hosts
  set_fact:
    already_initialized: "{{ first_master.stat.exists }}"
  with_items: "{{ play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: yes

- name: Create the first master node
  command: "kubeadm init --config=/etc/kubeadm/config.yaml{%if node_name is defined %} --node-name {{ node_name }}{% endif %}"
  when: not already_initialized

- name: Fetch the kubectl configuration on localhost
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubernetes_kubeconfig_file }}"
    flat: yes

- include_tasks: configure_kubectl.yml

# Hack : k8s_info wait parameter skips if resource doesn't exists
- name: Waits for the control plane to be fully up
  k8s_info:
    kind: Pod
    name: "{{ item }}-{{ node_name | default(ansible_nodename) }}"
    namespace: kube-system
    kubeconfig: "{{ kubernetes_kubeconfig_file }}"
  register: result
  until: >-
    result.resources|length > 0
    and "containerStatuses" in result.resources[0].status
    and result.resources[0].status.containerStatuses|length > 0
    and result.resources[0].status.containerStatuses[0].ready
  retries: 10
  delay: 30
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  delegate_to: localhost
