---
- name: Prerequisites
  include_tasks: pre-requis.yml

- name: Construct the api_endpoint url
  set_fact:
    api_endpoint_tmp: "{{ kubernetes_control_plane_endpoint | default(ansible_fqdn) }}"
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes

- name: Set the fact api_endpoint for all play hosts
  set_fact:
    api_endpoint: "{{ api_endpoint_tmp }}"
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  run_once: yes

- name: Ensure kubeadm configuration directory exists
  file:
    state: directory
    path: /etc/kubeadm
    mode: 0755

- name: Copy the kubeadm init config
  template:
    src: kubeadm_config.yaml.j2
    dest: /etc/kubeadm/config.yaml
    mode: 0755
  when: '"kubernetes_masters" in group_names'

- name: Install first master node
  include_tasks: init_master.yml
  when: 'inventory_hostname == kubernetes_kubeadm_target'

- name: Install cni
  include_tasks: "cni/cni_{{ kubernetes_cni_driver }}.yml"

- include_tasks: get_nodes.yml
  run_once: yes

- name: Join other nodes
  include_tasks: join_node.yml
  when: 'inventory_hostname != kubernetes_kubeadm_target and node_name|default(ansible_nodename) not in nodes'

- include_tasks: get_nodes.yml
  run_once: yes

- name: Activate kubelet service on boot
  systemd:
    name: kubelet
    enabled: yes

- name: Wait for nodes to be in Ready state
  shell: |
    set -o pipefail;
    kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes | grep "{{ item }}  *Ready "
  args:
    executable: /bin/bash
  register: result
  until: result.rc == 0
  retries: 10
  delay: 30
  changed_when: false
  with_items: "{{ nodes }}"
  delegate_to: "{{ kubernetes_kubeadm_target }}"
  run_once: yes

- name: Post-configuration
  include_tasks: post_configuration.yml

- block:
  - name: Check for upgrades
    include_tasks: upgrade/check_upgrades.yml
    run_once: yes

  - name: Upgrade cluster
    include_tasks: upgrade/upgrade_cluster.yml
    when: need_upgrade

  any_errors_fatal: true
  when: kubernetes_upgrades_allowed
