- name: Fetch the CSRs in kubernetes
  k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    kubeconfig: "{{ kubernetes_kubeconfig_file }}"
  register: csrList
  delegate_to: localhost
  run_once: yes

- name: Approve kubelet CSRs
  command: "kubectl certificate approve {{ item.name }}"
  when: 'item.conditions is none and "system:nodes" in item.groups'
  with_items: "{{ csrList | json_query('resources[].{name: metadata.name, groups: spec.groups, conditions: status.conditions[].type}') }}"
  delegate_to: "{{ groups['kubernetes_masters'][0] }}"
  run_once: yes

- block:
  - name: Configure metrics-server (rbac/service/etc...)
    k8s:
      state: present
      src: "{{ role_path }}/files/metrics-server-config.yaml.src"
      kubeconfig: "{{ kubernetes_kubeconfig_file }}"
    changed_when: false

  - name: Deploy metrics-server
    k8s:
      state: present
      definition: "{{ lookup('template', role_path + '/templates/metrics-server-deployment.yaml.j2') }}"
      kubeconfig: "{{ kubernetes_kubeconfig_file }}"
      wait_timeout: 600
      wait: "{{ metrics_server_wait_deploy }}"
  delegate_to: localhost
  run_once: yes
