- name: Gather the package facts
  package_facts:

- name: Package manager configuration for RHEL
  block:
  - name: Configure yum
    template:
      src: "{{ item }}"
      dest: "/etc/yum.repos.d/"
      mode: 0644
    with_fileglob:
      - "../templates/*.repo"

  - name: Install kubernetes packages (RHEL)
    yum:
      name:
        - kubelet-{{ kubernetes_version }}
        - kubeadm-{{ kubernetes_version }}
        - kubectl-{{ kubernetes_version }}
      enablerepo: kubernetes
      state: present
  when: '"kubeadm" not in ansible_facts.packages and ansible_os_family == "RedHat"'

- name: Package manager configuration for Debian
  block:
  - name: Get Google Cloud public signing key
    get_url:
      url: "{{ kubernetes_apt_key_url }}"
      dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
      mode: '0644'

  - name: Configure apt
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] {{ kubernetes_apt_repository }} kubernetes-xenial main"
      state: present

  - name: Install kubernetes packages (deb)
    apt:
      update_cache: true
      name:
        - kubelet={{ kubernetes_version }}-00
        - kubeadm={{ kubernetes_version }}-00
        - kubectl={{ kubernetes_version }}-00
      state: present
  when: '"kubeadm" not in ansible_facts.packages and ansible_os_family == "Debian"'

- name: Ensure ipvs kernel modules are loadable
  modprobe:
    name: "{{ item }}"
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
  when: kubernetes_proxy_mode == "ipvs"

- name: Ensure br_netfilter module is loaded
  modprobe:
    name: br_netfilter

- name: Install IPSet package
  package:
    name: ipset
    state: present
  when: kubernetes_proxy_mode == "ipvs"

- name: Ensure other modules are loaded
  modprobe:
    name: br_netfilter

- name: Ensure openvswitch module is loaded
  modprobe:
    name: openvswitch
  when: kubernetes_cni_driver == "antrea"

- name: Configure kernel module on boot
  template:
    src: kubernetes-modules.load.j2
    dest: /etc/modules-load.d/kubernetes
    mode: 0644

- name: Set sysctl parameters required by kubernetes
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_file: "/etc/sysctl.d/k8s.conf"
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
