---
- name: Converge
  hosts: all
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        kubernetes_image_repository: "{{ lookup('env', 'K8S_REGISTRY_MIRROR') }}"
        flannel_image: "{{ lookup('env', 'QUAY_REGISTRY_MIRROR') }}/coreos/flannel"
        metrics_server_image: "{{ lookup('env', 'K8S_REGISTRY_MIRROR') }}/metrics-server/metrics-server"
        kubernetes_yum_repo: "{{ lookup('env', 'K8S_YUM_MIRROR') }}"
        kubernetes_apt_repository: "{{ lookup('env', 'K8S_APT_MIRROR') }}"
        kubernetes_yum_enable_gpg: false
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'http_proxy') }}"
    HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY') }}"
    HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
    NO_PROXY: "{{ lookup('env', 'NO_PROXY') }}"
