---
dependency:
  name: shell
  command: "/bin/bash molecule/commun/dependencies.sh"
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: lb
    box: centos/7
    memory: 1024
    cpus: 1
    provider_options:
      connect_via_ssh: ${REMOTE_HOST:-false}
    provider_raw_config_args: ${PROVIDER_ARGS:-"[]"}
    groups:
      - loadbalancer
  - name: 3-master1
    box: centos/7
    memory: 2048
    cpus: 2
    provider_options:
      connect_via_ssh: ${REMOTE_HOST:-false}
    provider_raw_config_args: ${PROVIDER_ARGS:-"[]"}
    groups:
      - kubernetes_masters
      - kubernetes
      - containerd
  - name: 3-master2
    box: centos/7
    memory: 2048
    cpus: 2
    provider_options:
      connect_via_ssh: ${REMOTE_HOST:-false}
    provider_raw_config_args: ${PROVIDER_ARGS:-"[]"}
    groups:
      - kubernetes_masters
      - kubernetes
      - containerd
  - name: 3-master3
    box: centos/7
    memory: 2048
    cpus: 2
    provider_options:
      connect_via_ssh: ${REMOTE_HOST:-false}
    provider_raw_config_args: ${PROVIDER_ARGS:-"[]"}
    groups:
      - kubernetes_masters
      - kubernetes
      - containerd
  - name: 3-worker1
    box: centos/7
    memory: 2048
    cpus: 2
    provider_options:
      connect_via_ssh: ${REMOTE_HOST:-false}
    provider_raw_config_args: ${PROVIDER_ARGS:-"[]"}
    groups:
      - kubernetes_workers
      - kubernetes
      - containerd
  - name: 3-worker2
    box: centos/7
    memory: 2048
    cpus: 2
    provider_options:
      connect_via_ssh: ${REMOTE_HOST:-false}
    provider_raw_config_args: ${PROVIDER_ARGS:-"[]"}
    groups:
      - kubernetes_workers
      - kubernetes
      - containerd
provisioner:
  name: ansible
  config_options:
      ssh_connection:
        ssh_args: ${SSH_ARGS:-""}
  env:
    CONTAINERD_REGISTRY_MIRRORS: ${CONTAINERD_REGISTRY_MIRRORS}
    DOCKER_REGISTRY_MIRROR: ${DOCKER_REGISTRY_MIRROR}
    QUAY_REGISTRY_MIRROR: ${QUAY_REGISTRY_MIRROR}
    K8S_REGISTRY_MIRROR: ${K8S_REGISTRY_MIRROR}
    INSECURE_REGISTRIES: ${INSECURE_REGISTRIES}
    CENTOS_BASE_MIRROR: ${CENTOS_BASE_MIRROR}
    DEBIAN_BASE_MIRROR: ${DEBIAN_BASE_MIRROR}
    DOCKER_YUM_MIRROR: ${DOCKER_YUM_MIRROR}
    DOCKER_APT_MIRROR: ${DOCKER_APT_MIRROR}
    K8S_YUM_MIRROR: ${K8S_YUM_MIRROR}
    K8S_APT_MIRROR: ${K8S_APT_MIRROR}
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      3-master1:
        node_name: master1
        containerd_repo: ${DOCKER_YUM_MIRROR}
        kubernetes_api_server_advertise_address: "{{ansible_host}}"
      3-master2:
        node_name: master2
        containerd_repo: ${DOCKER_YUM_MIRROR}
        kubernetes_api_server_advertise_address: "{{ansible_host}}"
      3-master3:
        node_name: master3
        containerd_repo: ${DOCKER_YUM_MIRROR}
        kubernetes_api_server_advertise_address: "{{ansible_host}}"
      3-worker1:
        node_name: worker1
        containerd_repo: ${DOCKER_YUM_MIRROR}
      3-worker2:
        node_name: worker2
        containerd_repo: ${DOCKER_YUM_MIRROR}
verifier:
  name: testinfra
  directory: ../commun/tests/
  options:
    ssh-config: ../commun/tests/${SSH_CONFIG}
    hosts: 3-master1,3-master2,3-master3,3-worker1,3-worker2
  lint:
    name: flake8
